# Generated by Django 2.0.6 on 2019-11-30 05:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Contact', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Sex', models.CharField(max_length=10)),
                ('Birthday', models.DateTimeField(default=datetime.datetime.now)),
                ('Species', models.CharField(max_length=25)),
                ('Breed', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Source', models.CharField(max_length=50)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Owner')),
            ],
        ),
    ]
