# Generated by Django 2.0 on 2019-06-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='Total_Cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
