# Generated by Django 2.0 on 2019-06-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190613_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='List_Price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='products',
            name='User',
            field=models.ForeignKey(default='jerome', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
