# Generated by Django 2.0 on 2019-06-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190615_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Quantity',
        ),
    ]
