# Generated by Django 2.0 on 2019-06-18 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Products'),
        ),
    ]
