# Generated by Django 2.0 on 2019-07-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
