# Generated by Django 2.0 on 2019-06-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sales_list_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='List_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
