# Generated by Django 2.0 on 2019-06-21 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_products_quantity'),
        ('sales', '0003_sales_list_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempSalesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Total_Item_Price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Products')),
            ],
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='Quantity',
            new_name='OR',
        ),
        migrations.RenameField(
            model_name='saleslist',
            old_name='Sales_ID',
            new_name='SalesID',
        ),
        migrations.RenameField(
            model_name='saleslist',
            old_name='Price',
            new_name='Total_Item_Price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='List_Price',
        ),
        migrations.AddField(
            model_name='sales',
            name='Date_Recorded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
