# Generated by Django 2.0 on 2019-06-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20190621_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempsaleslist',
            name='Total_Item_Price',
        ),
        migrations.AlterField(
            model_name='tempsaleslist',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Purchase'),
        ),
    ]
