# Generated by Django 2.0 on 2019-06-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20190621_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslist',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Purchase'),
        ),
    ]
