# Generated by Django 2.0 on 2019-06-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20190621_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempsaleslist',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Purchase', unique=True),
        ),
    ]
