# Generated by Django 2.0 on 2019-06-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20190621_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Total_Sales',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
