# Generated by Django 2.0 on 2019-06-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20190622_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempsaleslist',
            name='Item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Purchase'),
        ),
    ]
