# Generated by Django 2.0 on 2019-07-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20190624_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslist',
            name='Item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Products'),
        ),
        migrations.AlterField(
            model_name='tempsaleslist',
            name='Item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Products'),
        ),
    ]
