# Generated by Django 2.0 on 2019-07-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20190703_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslist',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Products', unique=True),
        ),
    ]
